ecomm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace= 'home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('home.api_urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT
                          )

home/urls.py
from django.urls import path
from .views import *
app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name= 'home'),
    path('category/<slug>', CategoryView.as_view(), name= 'category'),
    path('products/<slug>', Product_detailView.as_view(), name= 'products'),
    path('search', SearchView.as_view(), name= 'search'),
    path('contact', contact, name= 'contact'),
    path('account', signup, name = 'account'),
    path('review', review_item, name= 'review'),
    path('cart/<slug>', cart, name='cart'),
    path('my_cart', CartView.as_view(), name= 'my_cart'),
    path('delete_cart/<slug>', delete_cart, name= 'delete_cart'),
    path('delete_single_cart/<slug>', delete_single_cart, name= 'delete_single_cart'),
    path('checkout', checkout, name='checkout'),
    path('checkouts', CheckoutView.as_view(), name= 'checkouts'),
    
]

home/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator


STATUS = (
    ('active', 'active'),
    ('inactive', 'inactive')
)
LABEL = (
    ('new', 'new'),
    ('hot', 'hot'),
    ('sale', 'sale'),
    ('', 'default')
)
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length= 200)
    image = models.CharField(max_length= 200)
    slug = models.CharField(max_length= 100, unique= True)
    status = models.CharField(choices= STATUS, max_length= 200)
    def __str__(self):
        return self.name

    def get_cat_url(self):
        return reverse("home:category", kwargs = {'slug':self.slug})

class Slider(models.Model):
    name = models.CharField(max_length= 300)
    image = models.ImageField(upload_to= 'media')
    discription = models.TextField(blank= True)
    status = models.CharField(choices=STATUS, max_length=200)
    def __str__(self):
        return self.name

class Ad(models.Model):
    name = models.CharField(max_length= 200)
    rank = models.IntegerField()
    image = models.ImageField(upload_to= 'media')
    discription = models.TextField(blank= True)
    status = models.CharField(choices=STATUS, max_length=200)
    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length= 200)
    image = models.ImageField(upload_to= 'media')
    status = models.CharField(choices=STATUS, max_length=200)
    def __str__(self):
        return self.name

class Item(models.Model):
    title = models.CharField(max_length= 200)
    name = models.CharField(max_length= 200, blank= True)
    price = models.IntegerField()
    discounted_price = models.IntegerField(default= 0)
    label = models.CharField(choices= LABEL, max_length= 200)
    image = models.ImageField(upload_to= 'media')
    status = models.CharField(max_length= 200, choices= STATUS)
    slug = models.CharField(max_length= 200, unique= True)
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete= models.CASCADE, null= True)
    discription = models.TextField(blank= True)
    specification = models.TextField(blank= True)
    def __str__(self):
        return self.name
    def get_item_url(self):
        return reverse("home:products", kwargs = {'slug':self.slug})
    def get_cart_url(self):
        return reverse("home:cart", kwargs = {'slug':self.slug})

class Feedback(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length= 200)
    profession = models.CharField(max_length= 100)
    discription = models.TextField()
    status = models.CharField(max_length=200, choices=STATUS, blank= True)
    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length= 200)
    email = models.EmailField(max_length= 200, blank= True)
    subject = models.CharField(max_length= 500, blank= True)
    message = models.TextField()
    def __str__(self):
        return self.name

class Review(models.Model):
    username = models.CharField(max_length= 250, blank= True)
    date = models.DateField(auto_now_add= True)
    email = models.EmailField(max_length= 250, blank=True)
    review = models.TextField(blank= True)
    rating = models.IntegerField()
    slug = models.CharField(max_length= 200, blank= True)
    status = models.CharField(choices= STATUS,max_length= 200, default= 'active')

    def __str__(self):
        return self.username

class Cart(models.Model):
    username = models.CharField(max_length=300)
    slug = models.CharField(max_length=300)
    items = models.ForeignKey(Item, on_delete=models.CASCADE, blank=True)
    quantity = models.IntegerField()
    total = models.IntegerField(default=0)
    all_total = models.IntegerField(default=0)
    checkout = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class Checkout(models.Model):
    username = models.CharField(max_length=300)
    fname = models.CharField(max_length=200, blank=True)
    lname = models.CharField(max_length=200,blank=True)
    email = models.EmailField(max_length=300,blank=True)
    mobile_no = models.CharField(max_length=50)
    address = models.CharField(max_length=500, blank=True)
    country = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.username

home/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import *
from django.contrib.auth.models import User
from django.contrib import messages


# Create your views here.


class BaseView(View):
    views = {}
    # views['cart_count'] = Cart.objects.filter().count()

class HomeView(BaseView):
    def get(self, request):
        self.views['categories'] = Category.objects.filter(status='active')
        self.views['sliders'] = Slider.objects.filter(status='active')
        self.views['hotitems'] = Item.objects.filter(label='hot')
        self.views['newitems'] = Item.objects.filter(label='new')
        self.views['sales'] = Item.objects.filter(label='sale')
        self.views['defaults'] = Item.objects.filter(label='')
        self.views['items'] = Item.objects.filter(status='active')
        self.views['brands'] = Brand.objects.filter(status= 'active')
        self.views['ads'] = Ad.objects.all()
        # self.views['ads2'] = Ad.objects.filter(rank= 2)
        self.views['feedbacks'] = Feedback.objects.filter(status= 'active')

        return render(request, 'index.html', self.views)

def review_item(request):
    if request.method == "POST":
        rating = request.POST['rating']
        review = request.POST['review']
        slug = request.POST['slug']
        username = request.user.username
        email = request.user.email
        user_review = Review.objects.create(
            rating = rating,
            review = review,
            username = username,
            email = email,
            slug = slug
        )
        user_review.save()
        return redirect(f'/products/{slug}')


class CategoryView(BaseView):
    def get(self, request, slug):
        cat_id = Category.objects.get(slug = slug).id
        self.views['cat_detail'] = Item.objects.filter(category= cat_id)

        return render(request, 'product-list.html', self.views)


class Product_detailView(BaseView):
    def get(self, request, slug):
        self.views['item_detail'] = Item.objects.filter(slug = slug)
        self.views['brand'] = Brand.objects.filter(status= 'active')
        self.views['reviews'] = Review.objects.filter(slug=slug,status= 'active')
        self.views['count'] = []
        for i in self.views['brand']:
            count_food = Item.objects.filter(brand = i.id).count()
            d = {'name':i.name, 'count':count_food}
            self.views['count'].append(d)

        self.views['cat_count'] = Category.objects.filter(status= 'active')
        self.views['count_cat'] = []
        for i in self.views['cat_count']:
            count_food = Item.objects.filter(category = i.id).count()
            dd = {'name':i.name, 'image':i.image,'count_cat':count_food}
            self.views['count_cat'].append(dd)

        cat = Item.objects.get(slug = slug).category_id
        self.views['cat_items'] = Item.objects.filter(category = cat)
        return render(request, 'product-detail.html', self.views)


class SearchView(BaseView):
    def get(self, request):
        # query = request.GET.get('search', None)
        if request.method == 'GET':
            query = request.GET['search']
            self.views['search_product'] = Item.objects.filter(discription__icontains = query)
            return render(request, 'search.html', self.views)
        return render(request, 'search.html')

def contact(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        data = Contact.objects.create(
            name = name,
            email = email,
            subject = subject,
            message = message
        )
        data.save()
        views = dict()
        views["message"] = "The Form is Submitted."
        return render(request, 'contact.html',views)
    return render(request, 'contact.html')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        fname = request.POST['fname']
        lname = request.POST['lname']
        if password == cpassword:
            if User.objects.filter(username = username).exists():
                messages.error(request, 'This username is already taken')
                return redirect('home:signup')

            elif User.objects.filter(email = email).exists():
                messages.error(request, 'This email is already taken')
                return redirect('home:account')

            else:
                user = User.objects.create_user(
                    username = username,
                    email = email,
                    password = password,
                    first_name = fname,
                    last_name = lname
                )
                user.save()
                messages.success(request, 'You are registered.')
                return redirect('home:account')

        else:
            messages.error(request, 'The password did not match.')
            return redirect('home:account')
    return render(request, 'signup.html')


def cart(request,slug):
    user = request.user.username
    price = Item.objects.get(slug=slug).price
    discounted_price = Item.objects.get(slug=slug).discounted_price
    if Cart.objects.filter(slug = slug).exists():
        quantity = Cart.objects.get(username = user, slug = slug, checkout = False).quantity
        qty = quantity + 1
        
        if discounted_price > 0:
            actual_total = discounted_price * qty
           
        else:
            actual_total = price * qty
        
        Cart.objects.filter(username=user, slug=slug, checkout=False).update(quantity= qty,total=actual_total)
        return redirect('home:my_cart')
    else:
        if discounted_price > 0:
            actual_total = discounted_price
        else:
            actual_total = price
        data = Cart.objects.create(
            username = user,
            slug = slug,
            quantity = 1,
            total = actual_total,
            items = Item.objects.filter(slug= slug)[0]
        )
        data.save()
        return redirect('home:my_cart')       


class CartView(BaseView):
    def get(self, request):
        user = request.user.username
        carts = Cart.objects.filter(username= user, checkout= False)
        self.views['cart_count'] = carts.count()
        self.views['cart_product'] = carts
        totals = 0
        shipping_cost = 100
        for each in carts:
            totals += each.total
        self.views['total_price'] = totals
        if totals == 0:
            shipping_cost = 0
            self.views['grand_total'] = 0
        else:
            self.views['grand_total'] = totals + shipping_cost
        self.views['shipping'] = shipping_cost
        return render(request, 'cart.html', self.views)


def delete_cart(request,slug):
    if Cart.objects.filter(slug = slug).exists():
        username = request.user.username
        Cart.objects.filter(username=username, slug=slug, checkout=False).delete()
    return redirect('home:my_cart')


def delete_single_cart(request,slug):
    if Cart.objects.filter(slug = slug).exists():
        username = request.user.username
        price = Item.objects.get(slug=slug).price
        discounted_price = Item.objects.get(slug=slug).discounted_price
        quantity = Cart.objects.get(username = username, slug = slug, checkout = False).quantity
        qty = quantity - 1
        if discounted_price > 0:
            actual_total = discounted_price * qty
        else:
            actual_total = price * qty
        Cart.objects.filter(username=username, slug=slug, checkout=False).update(quantity= qty, total= actual_total)
    return redirect('home:my_cart')


def checkout(request):
    if request.method == "POST":
        username = request.user.username,
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        mobile_no = request.POST['mobile_no']
        address = request.POST['address']
        country = request.POST['country']
        city = request.POST['city']
        if fname and lname and email != "":
            data = Checkout.objects.create(
                username = username,
                fname = fname,
                lname = lname,
                email = email,
                mobile_no = mobile_no,
                address = address,
                country = country,
                city = city,
            )
            data.save()
            Cart.objects.all().delete()
            return redirect('/')
        else:
            messages.error(request, 'Field must not be empty')
            return redirect('home:checkouts')
    return redirect('home:checkouts')

class CheckoutView(BaseView):
    def get(self, request):
        user = request.user.username
        carts = Cart.objects.filter(username= user, checkout= False)
        self.views['cart_product'] = carts
        totals = 0
        shipping_cost = 100
        for each in carts:
            totals += each.total
        self.views['total_price'] = totals
        if totals == 0:
            shipping_cost = 0
            self.views['grand_total'] = 0
        else:
            self.views['grand_total'] = totals + shipping_cost
        self.views['shipping'] = shipping_cost
        return render(request, 'checkout.html', self.views)


# # ------------------------------------------------API----------------------------------------------------
from .serializers import *
from django.contrib.auth.models import User
from .serializers import ItemSerializer
from rest_framework import generics
from rest_framework.filters import OrderingFilter,SearchFilter
from django_filters.rest_framework import DjangoFilterBackend

# ViewSets define the view behavior.

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Reason Ecommerce</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <i class="fa fa-envelope"></i>
                        support@email.com
                    </div>
                    <div class="col-sm-6">
                        <i class="fa fa-phone-alt"></i>
                        +012-345-6789
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar End -->

        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="/" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact Us</a>
                        </div>
                        <div class="navbar-nav ml-auto">
                            <div class="nav-item dropdown">
                                {% if user.is_authenticated %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{user.username}}</a>
                                <div class="dropdown-menu">
                                    <a href="/accounts/logout" class="dropdown-item">Logout</a>
                                </div>
                                {% else %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">User Account</a>
                                <div class="dropdown-menu">
                                    <a href="/accounts/login" class="dropdown-item">Log In</a>
                                    <a href="{% url 'home:account' %}" class="dropdown-item">Signup</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->

        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="index.html">
                                <img src="{% static 'img/logo.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form  method="GET" action="{% url 'home:search' %}">
                            <div class="search">
                                <input name = 'search' type="text" placeholder="Search">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <a href="{% url 'home:my_cart' %}" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>({{cart_count}})</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->

    {% block content%}

        {% endblock %}


     <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>123 E Store, Los Angeles, USA</p>
                                <p><i class="fa fa-envelope"></i>email@example.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Pyament Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="{% static 'img/payment-method.png' %}" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="{% static 'img/godaddy.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/norton.svg' %}" alt="Payment Security" />
                            <img src="{% static 'img/ssl.svg' %}" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

home/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Cart</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Cart Start -->
        <div class="cart-page">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Product</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Total</th>
                                            <th>Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                        {% for carts in cart_product %}
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <a href="#"><img src="{{carts.items.image.url}}" alt="Image"></a>
                                                    <p>{{carts.items.name}}</p>
                                                </div>
                                            </td>
                                            <td>Rs.{{carts.items.discounted_price}}</td>
                                            <td>
                                                <div class="qty">
                                                    <a href="delete_single_cart/{{carts.items.slug}}"><button class="btn-minus"><i class="fa fa-minus"></i></button></a>
                                                    <input type="text" value="{{carts.quantity}}">
                                                    <a href="{{carts.items.get_cart_url}}"><button class="btn-plus"><i class="fa fa-plus"></i></button></a>
                                                </div>
                                            </td>
                                            <td>Rs.{{carts.total}}</td>
                                            <td><a href="delete_cart/{{carts.items.slug}}"><button><i class="fa fa-trash"></i></button></a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-page-inner">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="coupon">
                                        <input type="text" placeholder="Coupon Code">
                                        <button>Apply Code</button>
                                    </div>
                                </div>
                                
                                <div class="col-md-12">
                                    {% comment %} {% for i in cart_product %} {% endcomment %}
                                    <div class="cart-summary">
                                        <div class="cart-content">
                                            <h1>Cart Summary</h1>
                                            <p>Sub Total<span>Rs.{{total_price}}</span></p>
                                            <p>Shipping Cost<span>Rs.{{shipping}}</span></p>
                                            <h2>Grand Total<span>Rs.{{grand_total}}</span></h2>
                                        </div>
                                        <div class="cart-btn">
                                            <a href={% url 'home:checkout' %}><button>Checkout</button></a>
                                        </div>
                                    </div>
                                   {% comment %} {% endfor %} {% endcomment %}
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <!-- Cart End -->
        {% endblock %}